---
- name: Install nginx
  hosts: 34.201.105.44
  become: true

  tasks:
- name: add epel-release repo
  apt-get:
    name: epel-release
    state: present

- name: Install nginx
  apt-get:
    name: nginx
    state: present

- name: Insert Index Page
  template:
    src: index.html
    dest: /home/ubuntu/index.html

- name: Start NGiNX
  service: started
...
